import 'package:flutter/material.dart';
import 'package:dio/dio.dart';
import '../core/network/dio_client.dart';
import '../data/models/purchase_request_model.dart';

class PurchaseProvider extends ChangeNotifier {
  final Dio _dio = DioClient().dio;

  List<PurchaseRequestModel> _requests = [];
  bool _isLoading = false;
  String? _error;

  List<PurchaseRequestModel> get requests => _requests;
  bool get isLoading => _isLoading;
  String? get error => _error;

  Future<void> fetchRequests() async {
    _isLoading = true;
    _error = null;
    notifyListeners();

    try {
      final response = await _dio.get('/purchase_requests');
      final List data = response.data;
      _requests = data.map((e) => PurchaseRequestModel.fromJson(e)).toList();
    } catch (e) {
      _error = 'Failed to load purchase requests: $e';
      print(_error);
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }

  Future<bool> createRequest(PurchaseRequestModel request) async {
    _isLoading = true;
    notifyListeners();

    try {
      // In a real api, ID is generated by backend.
      // mocking it here for json-server or if backend expects it.
      // We'll let json-server handle ID generation usually, but let's see.
      await _dio.post(
        '/purchase_requests',
        data: request.toJson()..remove('id'),
      );
      await fetchRequests(); // Refresh list
      return true;
    } catch (e) {
      _error = 'Failed to create request: $e';
      print(_error);
      _isLoading = false;
      notifyListeners();
      return false;
    }
  }

  Future<bool> updateStatus(
    String id,
    String status, {
    String? reason,
    String? approvedBy,
  }) async {
    _isLoading = true;
    notifyListeners();

    try {
      final data = {
        'status': status,
        if (approvedBy != null) 'approved_by': approvedBy,
        if (reason != null) 'rejection_reason': reason,
      };

      await _dio.patch('/purchase_requests/$id', data: data);
      await fetchRequests();
      return true;
    } catch (e) {
      _error = 'Failed to update status: $e';
      print(_error);
      _isLoading = false;
      notifyListeners();
      return false;
    }
  }
}
